/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package kutebabank;

import javax.lang.model.SourceVersion;

/**
 *
 * @author 20eli
 */
public class Transfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package kutebabank;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Transfer form for transferring balance between accounts
 */
public class Transfer extends javax.swing.JInternalFrame {

    public Transfer() {
        initComponents();
    }

    /**
     * Perform the balance transfer between two accounts.
     */
    public void performTransfer() {
        String fromAcc = jTextFieldFrom.getText().trim();
        String toAcc = jTextFieldTo.getText().trim();
        double amount;

        try {
            amount = Double.parseDouble(jTextFieldAmount.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount.");
            return;
        }

        if (fromAcc.equals(toAcc)) {
            JOptionPane.showMessageDialog(this, "Cannot transfer to the same account.");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/oopbank", "root", "");
            con.setAutoCommit(false); // Start transaction

            PreparedStatement pst = con.prepareStatement("SELECT balance FROM account WHERE acc_id = ?");
            pst.setString(1, fromAcc);
            ResultSet rs1 = pst.executeQuery();
            if (!rs1.next()) {
                JOptionPane.showMessageDialog(this, "Sender account not found.");
                return;
            }
            double senderBalance = rs1.getDouble("balance");

            pst.setString(1, toAcc);
            ResultSet rs2 = pst.executeQuery();
            if (!rs2.next()) {
                JOptionPane.showMessageDialog(this, "Receiver account not found.");
                return;
            }
            double receiverBalance = rs2.getDouble("balance");

            if (amount > senderBalance) {
                JOptionPane.showMessageDialog(this, "Insufficient funds.");
                return;
            }

            // Deduct from sender
            pst = con.prepareStatement("UPDATE account SET balance = ? WHERE acc_id = ?");
            pst.setDouble(1, senderBalance - amount);
            pst.setString(2, fromAcc);
            pst.executeUpdate();

            // Add to receiver
            pst.setDouble(1, receiverBalance + amount);
            pst.setString(2, toAcc);
            pst.executeUpdate();

            // Record transfer
            pst = con.prepareStatement("INSERT INTO transfer (from_acc_id, to_acc_id, date, amount) VALUES (?, ?, CURDATE(), ?)");
            pst.setString(1, fromAcc);
            pst.setString(2, toAcc);
            pst.setDouble(3, amount);
            pst.executeUpdate();

            con.commit(); // End transaction
            JOptionPane.showMessageDialog(this, "Transfer successful.");

            // Log to file
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("transfer_log.txt", true))) {
                writer.write("Transfer | From: " + fromAcc + " | To: " + toAcc +
                             " | Amount: " + amount + " | Date: " + java.time.LocalDate.now());
                writer.newLine();
            }

            // Clear fields
            jTextFieldAmount.setText("");
            jTextFieldFrom.setText("");
            jTextFieldTo.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Transfer failed.");
        }
    }

    // UI Initialization
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldFrom = new javax.swing.JTextField();
        jTextFieldTo = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24));
        jLabel1.setText("Transfer to Account");

        jTextFieldTo.addActionListener(evt -> jTextFieldToActionPerformed(evt));
        jTextFieldAmount.addActionListener(evt -> jTextFieldAmountActionPerformed(evt));

        jLabel2.setText("From");
        jLabel3.setText("To");
        jLabel4.setText("Amount");

        jButton1.setText("Transfer");
        jButton1.addActionListener(evt -> jButton1ActionPerformed(evt));

        jButton2.setText("Clear");
        jButton2.addActionListener(evt -> jButton2ActionPerformed(evt));

        jButton3.setText("Cancel");
        jButton3.addActionListener(evt -> jButton3ActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(136, 136, 136).addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup().addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel4))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3)
                                        .addComponent(jButton2)))))))
                    .addContainerGap(173, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
                    .addComponent(jLabel1)
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton3)
                    .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }

    // --- Button Actions ---
    private void jTextFieldToActionPerformed(java.awt.event.ActionEvent evt) {
        // Optional: Handle on enter
    }

    private void jTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {
        // Optional: Handle on enter
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        performTransfer();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldFrom.setText("");
        jTextFieldTo.setText("");
        jTextFieldAmount.setText("");
        jTextFieldFrom.requestFocus();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
    }

    // --- UI Component Declarations ---
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldTo;
}
