
package kutebabank;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
       
/**
 *
 * @author lenovo
 */
public class Withdraw extends javax.swing.JInternalFrame {

   

    public Withdraw() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     String currentCustId;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

public void search() {
    try {
        String acc_id = jTextField1.getText().trim(); 
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/oopbank", "root", "");

        pst = con.prepareStatement("""
            SELECT c.firstname, c.lastname, a.balance, a.cust_id
            FROM customer c
            JOIN account a ON c.cust_id = a.cust_id
            WHERE a.acc_id = ?
        """);
        pst.setString(1, acc_id);
        rs = pst.executeQuery();

        if (rs.next()) {
        String custname = rs.getString("firstname").trim() + " " + rs.getString("lastname").trim();
        jTextField2.setText(custname); // name
        jTextField3.setText(rs.getString("balance")); // balance
        currentCustId = rs.getString("cust_id"); // save for withdrawal
}       else {
    JOptionPane.showMessageDialog(this, "Account No Not Found");
}

    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
    }
}

public void withdraw() throws IOException {
    try {
        String acc_id = jTextField1.getText().trim();
        double balance = Double.parseDouble(jTextField3.getText().trim());
        double amount = Double.parseDouble(jTextField4.getText().trim());

        if (amount > balance) {
            JOptionPane.showMessageDialog(this, "Insufficient balance.");
            return;
        }

        double newBalance = balance - amount;

        
        pst = con.prepareStatement("INSERT INTO withdraw(acc_id, cust_id, date, amount) VALUES (?, ?, CURDATE(), ?)");
        pst.setString(1, acc_id);
        pst.setString(2, currentCustId);  
        pst.setDouble(3, amount);
        pst.executeUpdate();

        
        pst = con.prepareStatement("UPDATE account SET balance = ? WHERE acc_id = ?");
        pst.setDouble(1, newBalance);
        pst.setString(2, acc_id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Withdrawal successful.");
        jTextField3.setText(String.valueOf(newBalance));
        jTextField4.setText("");
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("withdraw_log.txt", true))) {
            writer.write("Withdrawal | Account ID: " + acc_id + " | Customer ID: " + currentCustId + 
                 " | Amount: " + amount + " | Date: " + java.time.LocalDate.now());
            writer.newLine();
    }   catch (IOException e) {
                e.printStackTrace();
    }

        

    } catch (SQLException ex) {
        Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
    }
}




    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtacc = new javax.swing.JLabel();
        txtcustname = new javax.swing.JLabel();
        txtbalance = new javax.swing.JLabel();
        txtamount = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Withdraw");

        txtacc.setText("Account No.");

        txtcustname.setText("Customer Name:");

        txtbalance.setText("Current Balance:");

        txtamount.setText("Withdraw Amount:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtamount)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcustname)
                            .addComponent(txtacc)
                            .addComponent(txtbalance))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnWithdraw)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtacc)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcustname)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbalance)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtamount)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(jButton3))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       setVisible(false);
             dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        try {
            withdraw();
        } catch (IOException ex) {
            System.getLogger(Withdraw.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    
    }//GEN-LAST:event_btnWithdrawActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtacc;
    private javax.swing.JLabel txtamount;
    private javax.swing.JLabel txtbalance;
    private javax.swing.JLabel txtcustname;
    // End of variables declaration//GEN-END:variables
}
